### ISSUE TITLE
How to reproduce the experimental results of SimulMask？

### ISSUE THREAD

**Issue by gpengzhi** [OSU-STARLAB/Simul-LLM#14]
I try to reproduce `SM-norec-mod (wait 5)` for `en -> nl` direction. But my scores (26.4 / 5.26) are much lower than yours (29.13 / 5.13) reported in the paper.

Here are my training and evaluation configurations:
```
CUDA_VISIBLE_DEVICES=0 python3 cli/finetune.py \
    --model models/falcon-rw-1b \
    --training-set iwslt2017 --training-subset iwslt2017-en-nl \
    --source-lang en --target-lang nl \
    --bsz 32 --update-freq 2 \
    --optim adamw_torch --lr 2e-4 --lr-scheduler inverse_sqrt --weight-decay 0.1 \
    --warmup-ratio 0.03 --max-grad-norm 1 \
    --save-strategy epoch --eval-interval 3707 --log-interval 1000 --num-train-epochs 2 \
    --max-seq-length 512 --waitk 9 --attmask-type simul \
    --user-dir examples/simulmask \
    --output-dir ckpt_${EXP} \
    --bnb-4bit-compute-dtype bfloat16
```

```
CUDA_VISIBLE_DEVICES=7 python3 cli/simuleval_wrapper.py \
    --agent examples/simulmask/falcon_simulmask_agent.py \
    --source testset/iwslt2017-en-nl.en \
    --target testset/iwslt2017-en-nl.nl \
    --source-lang en --target-lang nl \
    --model ${CKPT} \
    --output ckpt_eval \
    --waitk 5 --device cuda --attmask-type causal \
    --compute-dtype bfloat16 --quality-metric BLEU CHRF
```

I download the [released checkpoint](https://huggingface.co/raffelm/falcon-simulmask-en-nl)  and conduct the evaluation step. The results (29.099 / 5.143) are quite close to those in the paper. 

Did I miss any technical details? I look forward to your response.

**Comment by gpengzhi** [comment]
I check the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json) and [training arguments](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/training_args.bin). My training configs should be the same as yours. But the training losses (shown as follows) are larger than yours.

```
{'loss': 1.6551, 'learning_rate': 9.444575162494078e-05, 'epoch': 0.27}
{'loss': 1.0764, 'learning_rate': 6.678323142825601e-05, 'epoch': 0.54}
{'loss': 0.9503, 'learning_rate': 5.452828012447608e-05, 'epoch': 0.81}
{'eval_loss': 1.4410006999969482, 'eval_runtime': 5.5676, 'eval_samples_per_second': 180.148, 'eval_steps_per_second': 22.631, 'epoch': 1.0}
{'loss': 0.8097, 'learning_rate': 4.722287581247039e-05, 'epoch': 1.08}
{'loss': 0.6024, 'learning_rate': 4.223742416388575e-05, 'epoch': 1.35}
{'loss': 0.5898, 'learning_rate': 3.8557316642456684e-05, 'epoch': 1.62}
{'loss': 0.5874, 'learning_rate': 3.56971387408811e-05, 'epoch': 1.89}
{'eval_loss': 1.4610947370529175, 'eval_runtime': 5.5051, 'eval_samples_per_second': 182.195, 'eval_steps_per_second': 22.888, 'epoch': 2.0}
```

**Comment by gpengzhi** [comment]
BTW, from the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json), `val_loss` of epoch 1 is lower than that of epoch 2. Which checkpoint do you select for evaluation? @Meaffel

**Comment by Meaffel** [comment]
> BTW, from the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json), `val_loss` of epoch 1 is lower than that of epoch 2. Which checkpoint do you select for evaluation? @Meaffel

For consistency, all the model checkpoints used in the paper were from epoch 2.

**Comment by Meaffel** [comment]
> I check the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json) and [training arguments](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/training_args.bin). My training configs should be the same as yours. But the training losses (shown as follows) are larger than yours.
> 
> ```
> {'loss': 1.6551, 'learning_rate': 9.444575162494078e-05, 'epoch': 0.27}
> {'loss': 1.0764, 'learning_rate': 6.678323142825601e-05, 'epoch': 0.54}
> {'loss': 0.9503, 'learning_rate': 5.452828012447608e-05, 'epoch': 0.81}
> {'eval_loss': 1.4410006999969482, 'eval_runtime': 5.5676, 'eval_samples_per_second': 180.148, 'eval_steps_per_second': 22.631, 'epoch': 1.0}
> {'loss': 0.8097, 'learning_rate': 4.722287581247039e-05, 'epoch': 1.08}
> {'loss': 0.6024, 'learning_rate': 4.223742416388575e-05, 'epoch': 1.35}
> {'loss': 0.5898, 'learning_rate': 3.8557316642456684e-05, 'epoch': 1.62}
> {'loss': 0.5874, 'learning_rate': 3.56971387408811e-05, 'epoch': 1.89}
> {'eval_loss': 1.4610947370529175, 'eval_runtime': 5.5051, 'eval_samples_per_second': 182.195, 'eval_steps_per_second': 22.888, 'epoch': 2.0}
> ```

I will look into it. A minor mistake may have been made while transferring my implementation to the main branch of Simul-LLM.

**Comment by gpengzhi** [comment]
> > I check the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json) and [training arguments](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/training_args.bin). My training configs should be the same as yours. But the training losses (shown as follows) are larger than yours.
> > ```
> > {'loss': 1.6551, 'learning_rate': 9.444575162494078e-05, 'epoch': 0.27}
> > {'loss': 1.0764, 'learning_rate': 6.678323142825601e-05, 'epoch': 0.54}
> > {'loss': 0.9503, 'learning_rate': 5.452828012447608e-05, 'epoch': 0.81}
> > {'eval_loss': 1.4410006999969482, 'eval_runtime': 5.5676, 'eval_samples_per_second': 180.148, 'eval_steps_per_second': 22.631, 'epoch': 1.0}
> > {'loss': 0.8097, 'learning_rate': 4.722287581247039e-05, 'epoch': 1.08}
> > {'loss': 0.6024, 'learning_rate': 4.223742416388575e-05, 'epoch': 1.35}
> > {'loss': 0.5898, 'learning_rate': 3.8557316642456684e-05, 'epoch': 1.62}
> > {'loss': 0.5874, 'learning_rate': 3.56971387408811e-05, 'epoch': 1.89}
> > {'eval_loss': 1.4610947370529175, 'eval_runtime': 5.5051, 'eval_samples_per_second': 182.195, 'eval_steps_per_second': 22.888, 'epoch': 2.0}
> > ```
> 
> I will look into it. A minor mistake may have been made while transferring my implementation to the main branch of Simul-LLM.

Thanks a lot! 

I look forward to your update!

**Comment by Meaffel** [comment]
> > > I check the [training log](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/trainer_state.json) and [training arguments](https://huggingface.co/raffelm/falcon-simulmask-en-nl/blob/main/training_args.bin). My training configs should be the same as yours. But the training losses (shown as follows) are larger than yours.
> > > ```
> > > {'loss': 1.6551, 'learning_rate': 9.444575162494078e-05, 'epoch': 0.27}
> > > {'loss': 1.0764, 'learning_rate': 6.678323142825601e-05, 'epoch': 0.54}
> > > {'loss': 0.9503, 'learning_rate': 5.452828012447608e-05, 'epoch': 0.81}
> > > {'eval_loss': 1.4410006999969482, 'eval_runtime': 5.5676, 'eval_samples_per_second': 180.148, 'eval_steps_per_second': 22.631, 'epoch': 1.0}
> > > {'loss': 0.8097, 'learning_rate': 4.722287581247039e-05, 'epoch': 1.08}
> > > {'loss': 0.6024, 'learning_rate': 4.223742416388575e-05, 'epoch': 1.35}
> > > {'loss': 0.5898, 'learning_rate': 3.8557316642456684e-05, 'epoch': 1.62}
> > > {'loss': 0.5874, 'learning_rate': 3.56971387408811e-05, 'epoch': 1.89}
> > > {'eval_loss': 1.4610947370529175, 'eval_runtime': 5.5051, 'eval_samples_per_second': 182.195, 'eval_steps_per_second': 22.888, 'epoch': 2.0}
> > > ```
> > 
> > 
> > I will look into it. A minor mistake may have been made while transferring my implementation to the main branch of Simul-LLM.
> 
> Thanks a lot!
> 
> I look forward to your update!

I should have resolved the issue. The code had a bug caused by not passing the p1_len and p2_len  values to the make_simul_mask() function.

**Comment by gpengzhi** [comment]
Thanks for the quick fix!

I could reproduce the results now.

**Comment by Meaffel** [comment]
Thank you for bringing the issue to my attention.
