### ISSUE TITLE
Question on recomputing the KV cache

### ISSUE THREAD

**Issue by gpengzhi** [OSU-STARLAB/Simul-LLM#16]
If I understand it correctly, the results of the [checkpoint](https://huggingface.co/raffelm/falcon-simulmask-en-nl) of `SM-norec-mod` should be the same regardless of evaluating with or without recomputing the KV cache.

When I run
```
python3 cli/simuleval_wrapper.py \
    --agent examples/simulmask/falcon/falcon_simulmask_agent.py \
    --source testset/iwslt2017-en-nl.en \
    --target testset/iwslt2017-en-nl.nl \
    --source-lang en --target-lang nl \
    --model ../falcon-simulmask-en-nl \
    --output ckpt_eval \
    --waitk 5 --device cuda --attmask-type causal \
    --compute-dtype bfloat16 --quality-metric BLEU CHRF
```
I got
```
  BLEU   CHRF  LAAL    AL    AP   DAL   ATD
29.099 52.495 5.143 4.958 0.783 5.059 4.981
```

When I run
```
python3 cli/simuleval_wrapper.py \
    --agent examples/simulmask/falcon/falcon_simulmask_agent.py \
    --source testset/iwslt2017-en-nl.en \
    --target testset/iwslt2017-en-nl.nl \
    --source-lang en --target-lang nl \
    --model ../falcon-simulmask-en-nl \
    --output ckpt_eval \
    --waitk 5 --device cuda --attmask-type causal \
    --compute-dtype bfloat16 --quality-metric BLEU CHRF \
    --recompute-size 512
```
I got
```
 BLEU   CHRF  LAAL    AL    AP  DAL   ATD
25.14 51.469 5.596 4.941 1.033  5.8 5.538
```

Is such a big difference as expected? Thanks.

**Comment by Meaffel** [comment]
Yes, it is expected that the performance would be higher with KV caching.  The reason is that if we do not use KV caching, the hidden states for the target sequence will update for each new source input.  Fine-tuning with SimulMask does not model this behavior; instead, it models the scenario with KV caching where the target sequence is not updated for each new source input.  Therefore, it is expected to perform better with KV caching as it minimizes the fine-tuning inference mismatch.

**Comment by gpengzhi** [comment]
> Yes, it is expected that the performance would be higher with KV caching. The reason is that if we do not use KV caching, the hidden states for the target sequence will update for each new source input. Fine-tuning with SimulMask does not model this behavior; instead, it models the scenario with KV caching where the target sequence is not updated for each new source input. Therefore, it is expected to perform better with KV caching as it minimizes the fine-tuning inference mismatch.

I see. Thanks for the explanation.
