### ISSUE TITLE
Request for Sharing the Adapter Model of NMT LLM (Falcon or Llama2) on HuggingFace Hub

### ISSUE THREAD

**Issue by zhongmz** [OSU-STARLAB/Simul-LLM#4]
Hello,
I want to express my appreciation for your impressive work on SiMT community.

I am interested in obtaining the adapter model for NMT LLM (Falcon or Llama2) and would like to kindly request if you could consider sharing it on Huggingface Hub. Having access to this model would greatly benefit the research and development community, allowing for further exploration and experimentation.

Looking forward to your response. :)

**Comment by agostinv** [comment]
We’d be more than happy to! Was there a particular checkpoint that you had in mind (e.g. NMT LLM for en-de, wait-7 SimulMT LLM, etc.)? We’re running through some additional validation on our end that has been slowed down by maintenance at our institution, so I’ll prioritize what you’d like to see first. 

Llama and Mistral fine-tuning and validation has also unfortunately been slowed down. Some initial support that was lightly tested is available in a relevant branch on this repo.

**Comment by agostinv** [comment]
Sorry for the delay, things slowed down during the holidays. I'll provide this at the top of the repository, as well, but for ease of access you can find relevant checkpoints [here](https://drive.google.com/drive/folders/1yLySJN5r3Lr2uhO1HEpARiuo1pDli57D?usp=sharing).
